### PR TITLE
Added three Tideland projects

### PR DESCRIPTION
**Pull request by themue**

### CODE REVIEW

**Comment by mingrammer** [comment]
Are those all related to web development?

**Comment by themue** [comment]
Oh, sorry, hadn't noticed the restriction to web only. Here `gorest` is for web applications enabling easy and powerful RESTful APIs.

**Comment by mingrammer** [comment]
Yes, Could you left only that framework on list.txt?

**Comment by themue** [comment]
Done, now only https://github.com/tideland/gorest has been added.

**Comment by mingrammer** [comment]
Thanks for contributing :)

**Pull request merged**
